server:
  port: 7080

spring:
  application:
    # 服务名
    name: web-user
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_hello?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
  redis:
    database: 0
    host: 101.34.84.24
    port: 6379
    password: vanceChen

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chinasoft.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰规则
    map-underscore-to-camel-case: true

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.chinasoft.fmmall: debug
